[package]
name = "opald"
version.workspace = true
edition = "2024"

[dependencies]
anyhow = "1.0.104"
base64 = "0.23.1"
clap = { version = "4.6.7", features = ["derive"] }
futures = "0.3.34"
nostr-connect = "0.45"
nostr-sdk = "0.45"
opal-core = { path = "../opal-core" }
opal-notify = { path = "../opal-notify" }
opal-signer = { path = "../opal-signer" }
opal-status = { path = "../opal-status" }
qrcode = { version = "0.14.1", default-features = false, features = ["svg"] }
rustix = { version = "1.1.5", features = ["process"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url = "2.5.8"
zbus = { version = "5.19.0", default-features = false, features = ["tokio"] }
zeroize = { version = "1.9.0", features = ["serde", "derive"] }
zxcvbn = "3.1.1"

[dev-dependencies]
rustls = { version = "0.23", default-features = false }
