[package]
name = "opal-core"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "7.0.0"
nostr = { version = "0.45", features = ["nip04", "nip06", "nip44", "nip46", "nip49", "nip59", "os-rng"] }
oo7 = "0.6.0"
reqwest = { version = "0.13.5", default-features = false, features = ["rustls-no-provider"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
secrecy = "0.10.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.21"
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.6"
tracing = "0.1.44"
zeroize = "1.9.0"
